package ca.gc.ssc.eti.msa;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * A class to retrieve language-specific messages/strings
 * @author Generated by Eclipse
 *
 */
public class Messages {
	private static final String BUNDLE_NAME = "ca.gc.ssc.eti.msa.messages"; //$NON-NLS-1$

	private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle
			.getBundle(BUNDLE_NAME);

	private Messages() {
	}

	public static String getString(String key) {
		try {
			return RESOURCE_BUNDLE.getString(key);
		} catch (MissingResourceException e) {
			return '!' + key + '!';
		}
	}
}
